services:
  backend:
    build:
      context: .
      dockerfile: group10_backend/Dockerfile
    volumes:
      - static_volume:/app/static
      - sqlite_data:/app/db
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=group10_backend.settings

  frontend:
    build:
      context: .
      dockerfile: group10-project-frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - TURBOPACK_WATCH_MODE=poll

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/static
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  static_volume:
  sqlite_data: