# Generated by Django 5.1.7 on 2025-03-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('annotation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('policy_id', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('attributes', models.JSONField()),
                ('url', models.CharField(max_length=100)),
            ],
        ),
    ]
