# Generated by Django 5.1.7 on 2025-03-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='attributes',
        ),
        migrations.AddField(
            model_name='annotation',
            name='endId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='startId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='text',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
