# Generated by Django 5.1.7 on 2025-03-07 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_remove_annotation_attributes_annotation_endid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrettyPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pretty_print', models.CharField(max_length=5000)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.annotation')),
            ],
        ),
    ]
