# Generated by Django 5.1.7 on 2025-03-07 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_prettyprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanitizedPolicy',
            fields=[
                ('policy_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='policy_id',
        ),
        migrations.AddField(
            model_name='annotation',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='policies.sanitizedpolicy'),
        ),
    ]
