# Generated by Django 5.1.7 on 2025-03-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0004_sanitizedpolicy_remove_annotation_policy_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanitizedpolicy',
            name='sanitized_policy_html',
            field=models.TextField(null=True),
        ),
    ]
