# Generated by Django 5.1.7 on 2025-03-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0005_sanitizedpolicy_sanitized_policy_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanitizedpolicy',
            name='policy_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
