# Generated by Django 5.1.7 on 2025-03-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0006_sanitizedpolicy_policy_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanitizedpolicy',
            name='policy_name',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
