# Generated by Django 5.1.7 on 2025-03-25 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0007_alter_sanitizedpolicy_policy_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyTrustScore',
            fields=[
                ('policy_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='policies.sanitizedpolicy')),
                ('trust_score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('total_count', models.IntegerField(default=0)),
            ],
        ),
    ]
