# Generated by Django 5.0.2 on 2025-03-18 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0007_alter_sanitizedpolicy_policy_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='text',
            new_name='attributes',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='endId',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='startId',
        ),
    ]
