# Generated by Django 5.0.2 on 2025-03-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0008_rename_text_annotation_attributes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='attributes',
            new_name='text',
        ),
        migrations.AddField(
            model_name='annotation',
            name='endId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='startId',
            field=models.IntegerField(null=True),
        ),
    ]
