# Generated by Django 5.1.7 on 2025-03-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0008_policytrustscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policytrustscore',
            name='trust_score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
