# Generated by Django 5.0.2 on 2025-03-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0009_rename_attributes_annotation_text_annotation_endid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='pretty_print',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
