# Generated by Django 5.1.7 on 2025-03-25 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0009_alter_policytrustscore_trust_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='policytrustscore',
            name='total_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='policytrustscore',
            name='total_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
