# Generated by Django 5.0.2 on 2025-03-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0010_annotation_pretty_print'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='pretty_print',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
