# Generated by Django 5.1.7 on 2025-03-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0010_policytrustscore_total_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policytrustscore',
            name='total_score',
        ),
        migrations.RemoveField(
            model_name='policytrustscore',
            name='trust_score',
        ),
        migrations.AddField(
            model_name='policytrustscore',
            name='average_trust_score',
            field=models.DecimalField(decimal_places=1000000, default=0.0, max_digits=1000000),
        ),
    ]
