# Generated by Django 5.1.7 on 2025-03-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0011_remove_policytrustscore_total_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policytrustscore',
            name='average_trust_score',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
