# Generated by Django 5.0.2 on 2025-03-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0013_alter_annotation_pretty_print'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='segment',
            field=models.IntegerField(null=True),
        ),
    ]
