# Generated by Django 5.0.2 on 2025-03-30 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0014_annotation_segment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('category_description', models.CharField(max_length=5000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='annotation',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='policies.category'),
        ),
        migrations.DeleteModel(
            name='PrettyPrint',
        ),
    ]
