# Generated by Django 5.1.7 on 2025-04-06 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0012_alter_policytrustscore_average_trust_score'),
        ('policies', '0015_category_alter_annotation_category_and_more'),
    ]

    operations = [
    ]
