# Generated by Django 5.1.7 on 2025-05-06 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0016_merge_20250406_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policytrustscore',
            name='average_trust_score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='policytrustscore',
            name='total_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterUniqueTogether(
            name='annotation',
            unique_together={('policy', 'category', 'segment', 'startId', 'endId')},
        ),
    ]
