# Generated by Django 5.1.7 on 2025-05-11 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0017_alter_policytrustscore_average_trust_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policytrustscore',
            name='average_trust_score',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
